[package]
name = "plasma"
version = "0.1.0"
authors = ["Bram Geron <bram@bram.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
